### ISSUE TITLE
Add legend or text explanation for color

### ISSUE THREAD

**Issue by hcorson-dosch-usgs** [DOI-USGS/drought-timeline#14]
Currently not clear that color is scaled to duration

**Comment by aaarcher-usgs** [comment]
Draft legend has been added as of June 9, 2023 with #20

**Comment by aaarcher-usgs** [comment]
![image](https://github.com/DOI-USGS/drought-timeline/assets/19958841/3105ae0a-459c-49ed-b8fb-7f2501d00918)
