### ISSUE TITLE
Revise authorship

### ISSUE THREAD

**Issue by hcorson-dosch-usgs** [DOI-USGS/drought-timeline#32]
Currently the authorship reads:

> Authors
[Hayley Corson-Dosch](https://www.usgs.gov/staff-profiles/hayley-corson-dosch) lead the development of this website with [Althea A. Archer](https://www.usgs.gov/staff-profiles/althea-a-archer) and [Cee Nell](https://www.usgs.gov/staff-profiles/cee-nell). [Mandie Carr](https://www.usgs.gov/staff-profiles/amanda-carr) wrote the narration and directed the visual storytelling throughout the site. The USGS Vizlab, including Hayley Corson-Dosch, Althea Archer, Cee Nell, and [Elmera Adazpour](https://www.usgs.gov/staff-profiles/elmera-azadpour) provided editorial and design review. This data visualization was inspired by a chart made by [Scott Hamshaw](https://www.usgs.gov/staff-profiles/scott-hamshaw).

Two thoughts:
1. I think we should add a bit more detail to the development piece to more accurately attribute the work - I don't think it's fair to list me as the lead for the full viz. Maybe attribute leading the web development to me, with contributions from you and Cee, and then attribute leading the data analysis and chart development to you, Althea, with contributions from me.
2. Elmera should also be listed as contributing to the development - she contributed the inset map code in #10

**Comment by aaarcher-usgs** [comment]
Is this what you were thinking @hcorson-dosch-usgs

**Comment by aaarcher-usgs** [comment]
I almost think we could lose the "The USGS Vizlab ... " sentence?

**Comment by hcorson-dosch-usgs** [comment]
Yeah - looks good. Thanks for making those edits. Agreed that sentence could go.
